name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm ci  # Clean install
          npx cypress verify  # Verify Cypress installation

      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable  # Ensure Chrome is installed

      - name: Run tests
        run: npx cypress run --browser chrome
